In [4]:
#Paqueterias
import pandas as pd 
import matplotlib.pyplot as plt

In [5]:
datos_modelo = pd.read_csv('Datos_completos.csv')

In [6]:
datos_modelo.head(5)

pdv_id  mes_id  sku_id  ventas_totales  y_ventas_siguiente_mes  \
0       1       0       1               1                       1   
1       1       1       1               1                       0   
2       1       2       1               0                       0   
3       1       3       1               0                       0   
4       1       4       1               0                       0   

   ventas_totales_en_tienda_de_cada_mes  \
0                                     1   
1                                     5   
2                                     1   
3                                     1   
4                                     0   

   ventas_promedio_en_tienda_de_cada_mes  \
0                               0.033333   
1                               0.166667   
2                               0.033333   
3                               0.033333   
4                               0.000000   

   ventas_totales_en_tienda_de_cada_sku  \
0                                  2087   
1                                  2106   
2                                  2028   
3                                  1187   
4                                   695   

   ventas_promedio_en_tienda_de_cada_sku  ventas_totales_1_mes_pasado  ...  \
0                               1.260266                            0  ...   
1                               1.271739                            1  ...   
2                               1.224638                            1  ...   
3                               0.716787                            0  ...   
4                               0.419686                            0  ...   

   ventas_totales_tienda_y_mes_3_pasado  \
0                                     0   
1                                     0   
2                                     0   
3                                     1   
4                                     5   

   ventas_promedio_tienda_y_mes_del_mes_pasado  \
0                                     0.000000   
1                                     0.033333   
2                                     0.166667   
3                                     0.033333   
4                                     0.033333   

   ventas_promedio_tienda_y_mes_2_pasado  \
0                               0.000000   
1                               0.000000   
2                               0.033333   
3                               0.166667   
4                               0.033333   

   ventas_promedio_tienda_y_mes_3_pasado  \
0                               0.000000   
1                               0.000000   
2                               0.000000   
3                               0.033333   
4                               0.166667   

   ventas_totales_tienda_y_sku_del_mes_pasado  \
0                                           0   
1                                        2087   
2                                        2106   
3                                        2028   
4                                        1187   

   ventas_totales_tienda_y_sku_2_pasado  ventas_totales_tienda_y_sku_3_pasado  \
0                                     0                                     0   
1                                     0                                     0   
2                                  2087                                     0   
3                                  2106                                  2087   
4                                  2028                                  2106   

   ventas_promedio_tienda_y_sku_del_mes_pasado  \
0                                     0.000000   
1                                     1.260266   
2                                     1.271739   
3                                     1.224638   
4                                     0.716787   

   ventas_promedio_tienda_y_sku_2_pasado  \
0                               0.000000   
1                               0.000000   
2                              

In [7]:
datos_modelo.shape

(447120, 24)

In [8]:
datos_modelo.columns

Index(['pdv_id', 'mes_id', 'sku_id', 'ventas_totales',
       'y_ventas_siguiente_mes', 'ventas_totales_en_tienda_de_cada_mes',
       'ventas_promedio_en_tienda_de_cada_mes',
       'ventas_totales_en_tienda_de_cada_sku',
       'ventas_promedio_en_tienda_de_cada_sku', 'ventas_totales_1_mes_pasado',
       'ventas_totales_2_meses_pasados', 'ventas_totales_3_meses_pasados',
       'ventas_totales_tienda_y_mes_del_mes_pasado',
       'ventas_totales_tienda_y_mes_2_pasado',
       'ventas_totales_tienda_y_mes_3_pasado',
       'ventas_promedio_tienda_y_mes_del_mes_pasado',
       'ventas_promedio_tienda_y_mes_2_pasado',
       'ventas_promedio_tienda_y_mes_3_pasado',
       'ventas_totales_tienda_y_sku_del_mes_pasado',
       'ventas_totales_tienda_y_sku_2_pasado',
       'ventas_totales_tienda_y_sku_3_pasado',
       'ventas_promedio_tienda_y_sku_del_mes_pasado',
       'ventas_promedio_tienda_y_sku_2_pasado',
       'ventas_promedio_tienda_y_sku_3_pasado'],
      dtype='object')

In [9]:
datos_modelo.head(1)

pdv_id  mes_id  sku_id  ventas_totales  y_ventas_siguiente_mes  \
0       1       0       1               1                       1   

   ventas_totales_en_tienda_de_cada_mes  \
0                                     1   

   ventas_promedio_en_tienda_de_cada_mes  \
0                               0.033333   

   ventas_totales_en_tienda_de_cada_sku  \
0                                  2087   

   ventas_promedio_en_tienda_de_cada_sku  ventas_totales_1_mes_pasado  ...  \
0                               1.260266                            0  ...   

   ventas_totales_tienda_y_mes_3_pasado  \
0                                     0   

   ventas_promedio_tienda_y_mes_del_mes_pasado  \
0                                          0.0   

   ventas_promedio_tienda_y_mes_2_pasado  \
0                                    0.0   

   ventas_promedio_tienda_y_mes_3_pasado  \
0                                    0.0   

   ventas_totales_tienda_y_sku_del_mes_pasado  \
0                                           0   

   ventas_totales_tienda_y_sku_2_pasado  ventas_totales_tienda_y_sku_3_pasado  \
0                                     0                                     0   

   ventas_promedio_tienda_y_sku_del_mes_pasado  \
0                                          0.0   

   ventas_promedio_tienda_y_sku_2_pasado  \
0                                    0.0   

   ventas_promedio_tienda_y_sku_3_pasado  
0                                    0.0  

[1 rows x 24 columns]

Recordar como leer los datos:

* En el punto de venta __1 (pdv_id = 1)__ , en el mes de __junio (mes_id = 0)__, el producto __1 (sku_id = 1)__, tuvo 2 ventas (ventas_totales = 2). 

* El pronóstico para el siguiente mes (julio - 1) tiene que ser lo más cercano a __0 (y_ventas_siguiente_mes = 0)__. 

* Las demás variables se leen de manera similar: El punto de venta __1 (pdv_id = 1)__ tuvo un total 23 ventas (ventas_totales_en_tienda_de_cada_mes = 23) en todo el mes de junio (sku_id = 1). 

* El 0 es un dato real, nosotros ya conocemos cuáles son las ventas para el siguiente mes porque contamos con históricos - nosotros construimos nuestra variable __Y__. 

* Ahora queremos contruir un modelo que nos permita estimar el valor de esta Y ->  __Y^__)

# Validación Cruzada

In [10]:
#1. DIVIR DATOS EN ENTRENAMIENTO Y PRUEBA
ent_1 = datos_modelo[datos_modelo['mes_id']==0]
prueba_1 = datos_modelo[datos_modelo['mes_id']==1]

In [11]:
ent_1.shape

(49680, 24)

In [12]:
prueba_1.shape

(49680, 24)

In [13]:
#2. GENERAR ÍNDICES EN PYTHON 
ent_1.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)
prueba_1.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)

In [14]:
#head para ver datos de entrenamiento y prueba con índices 

In [15]:
#3. DIVIDIR AMBOS CONJUNTOS (ENTRENAMIENTO Y PRUEBA) EN VARIABLES DE ENTRADA (X) Y VARIABLE REPSUESTA (Y)
ent_x1 = ent_1.iloc[:, ent_1.columns != 'y_ventas_siguiente_mes']
ent_y1 = ent_1.iloc[:, ent_1.columns == 'y_ventas_siguiente_mes']

prueba_x1= prueba_1.iloc[:, prueba_1.columns != 'y_ventas_siguiente_mes']
prueba_y1= prueba_1.iloc[:, prueba_1.columns == 'y_ventas_siguiente_mes']

----------------------Segunda Partición-------------------------

In [16]:
#1. DIVIR DATOS EN ENTRENAMIENTO Y PRUEBA
ent_2 = datos_modelo[datos_modelo['mes_id']<=1]
prueba_2 = datos_modelo[datos_modelo['mes_id']==2]

In [17]:
#2. GENERAR ÍNDICES EN PYTHON 
ent_2.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)
prueba_2.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)

In [18]:
#3. DIVIDIR AMBOS CONJUNTOS (ENTRENAMIENTO Y PRUEBA) EN VARIABLES DE ENTRADA (X) Y VARIABLE REPSUESTA (Y)
ent_x2 = ent_2.iloc[:, ent_2.columns != 'y_ventas_siguiente_mes']
ent_y2 = ent_2.iloc[:, ent_2.columns == 'y_ventas_siguiente_mes']

prueba_x2= prueba_2.iloc[:, prueba_2.columns != 'y_ventas_siguiente_mes']
prueba_y2= prueba_2.iloc[:, prueba_2.columns == 'y_ventas_siguiente_mes']

----------------------Tercera Partición-------------------------

In [19]:
ent_3 = datos_modelo[datos_modelo['mes_id']<=2]
prueba_3 = datos_modelo[datos_modelo['mes_id']==3]

In [20]:
ent_3.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)
prueba_3.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)

In [21]:
ent_x3 = ent_3.iloc[:, ent_3.columns != 'y_ventas_siguiente_mes']
ent_y3 = ent_3.iloc[:, ent_3.columns == 'y_ventas_siguiente_mes']

prueba_x3= prueba_3.iloc[:, prueba_3.columns != 'y_ventas_siguiente_mes']
prueba_y3= prueba_3.iloc[:, prueba_3.columns == 'y_ventas_siguiente_mes']

----------------------Cuarta Partición-------------------------

In [22]:
ent_4 = datos_modelo[datos_modelo['mes_id']<=3]
prueba_4 = datos_modelo[datos_modelo['mes_id']==4]

In [23]:
ent_4.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)
prueba_4.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)

In [24]:
ent_x4 = ent_4.iloc[:, ent_4.columns != 'y_ventas_siguiente_mes']
ent_y4 = ent_4.iloc[:, ent_4.columns == 'y_ventas_siguiente_mes']

prueba_x4= prueba_4.iloc[:, prueba_4.columns != 'y_ventas_siguiente_mes']
prueba_y4= prueba_4.iloc[:, prueba_4.columns == 'y_ventas_siguiente_mes']

----------------------Quinta Partición-------------------------

In [25]:
ent_5 = datos_modelo[datos_modelo['mes_id']<=4]
prueba_5 = datos_modelo[datos_modelo['mes_id']==5]

In [26]:
ent_5.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)
prueba_5.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)

In [27]:
ent_x5 = ent_5.iloc[:, ent_5.columns != 'y_ventas_siguiente_mes']
ent_y5 = ent_5.iloc[:, ent_5.columns == 'y_ventas_siguiente_mes']

prueba_x5= prueba_5.iloc[:, prueba_5.columns != 'y_ventas_siguiente_mes']
prueba_y5= prueba_5.iloc[:, prueba_5.columns == 'y_ventas_siguiente_mes']

----------------------Sexta Partición-------------------------

In [28]:
ent_6 = datos_modelo[datos_modelo['mes_id']<=5]
prueba_6 = datos_modelo[datos_modelo['mes_id']==6]

In [29]:
ent_6.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)
prueba_6.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)

In [30]:
ent_x6 = ent_6.iloc[:, ent_6.columns != 'y_ventas_siguiente_mes']
ent_y6 = ent_6.iloc[:, ent_6.columns == 'y_ventas_siguiente_mes']

prueba_x6= prueba_6.iloc[:, prueba_6.columns != 'y_ventas_siguiente_mes']
prueba_y6= prueba_6.iloc[:, prueba_6.columns == 'y_ventas_siguiente_mes']

----------------------Séptima Partición-------------------------

In [31]:
ent_7 = datos_modelo[datos_modelo['mes_id']<=6]
prueba_7 = datos_modelo[datos_modelo['mes_id']==7]

In [32]:
ent_7.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)
prueba_7.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)

In [33]:
ent_x7 = ent_7.iloc[:, ent_7.columns != 'y_ventas_siguiente_mes']
ent_y7 = ent_7.iloc[:, ent_7.columns == 'y_ventas_siguiente_mes']

prueba_x7= prueba_7.iloc[:, prueba_7.columns != 'y_ventas_siguiente_mes']
prueba_y7= prueba_7.iloc[:, prueba_7.columns == 'y_ventas_siguiente_mes']

----------------------Octava Partición-------------------------

In [34]:
ent_8 = datos_modelo[datos_modelo['mes_id']<=7]
prueba_8 = datos_modelo[datos_modelo['mes_id']==8]

In [35]:
ent_8.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)
prueba_8.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)

In [36]:
ent_x8 = ent_8.iloc[:, ent_8.columns != 'y_ventas_siguiente_mes']
ent_y8 = ent_8.iloc[:, ent_8.columns == 'y_ventas_siguiente_mes']

prueba_x8= prueba_8.iloc[:, prueba_8.columns != 'y_ventas_siguiente_mes']
prueba_y8= prueba_8.iloc[:, prueba_8.columns == 'y_ventas_siguiente_mes']

# Modelo Profundidad 1

In [37]:
#!pip install numpy
import numpy as np #determinar un rango de valores "clip"
from sklearn import tree #importar función para construir árboles
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error #errores que queremos calcular 
#from scipy.stats import sem
import warnings; warnings.simplefilter('ignore')#WARNING EN 3.3

In [154]:
# 1. CONSTRUIR MODELO
modelo_1 = tree.DecisionTreeRegressor(max_depth=1)

In [155]:
# 2. ENTRENAMOS EL MODELO (.FIT)
modelo_1.fit(ent_x1, ent_y1)

DecisionTreeRegressor(max_depth=1)

In [156]:
# 3. HACER PREDICCIONES: CALCULAR ERROR DE ENTRENAMIENTO 
pred1_ent = modelo_1.predict(ent_x1) 
pred1_ent

array([0.16563895, 0.16563895, 0.16563895, ..., 0.16563895, 0.16563895,
       0.16563895])

In [41]:
# 3.1 CALCULAR MÁXIMOS Y MÍNIMOS DE PREDICCIÓN (PARA VER RANGO DE PREDICCIÓN) - max() - min()

In [42]:
# 3.2 REDONDEAR Y AJUSTAR VALORES
pred1_ent = np.clip(pred1_ent,0,20).round() #rango de valores 
pred1_ent

array([0., 0., 0., ..., 0., 0., 0.])

In [43]:
# 3.3 JUNTAR DATOS PARA PODER CALCULAR ERROR
ent_1['ventas_por_mes_pred'] = pred1_ent

In [44]:
ent_1.head(5)

ventas_totales  y_ventas_siguiente_mes  \
pdv_id mes_id sku_id                                           
1      0      1                    1                       1   
              2                    0                       2   
              3                    0                       1   
              4                    0                       1   
              5                    0                       0   

                      ventas_totales_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                         
1      0      1                                          1   
              2                                          1   
              3                                          1   
              4                                          1   
              5                                          1   

                      ventas_promedio_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                          
1      0      1                                    0.033333   
              2                                    0.033333   
              3                                    0.033333   
              4                                    0.033333   
              5                                    0.033333   

                      ventas_totales_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                         
1      0      1                                       2087   
              2                                        888   
              3                                       1636   
              4                                       1250   
              5                                        607   

                      ventas_promedio_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                          
1      0      1                                    1.260266   
              2                                    0.536232   
              3                                    0.987923   
              4                                    0.754831   
              5                                    0.366546   

                      ventas_totales_1_mes_pasado  \
pdv_id mes_id sku_id                                
1      0      1                                 0   
              2                                 0   
              3                                 0   
              4                                 0   
              5                                 0   

                      ventas_totales_2_meses_pasados  \
pdv_id mes_id sku_id                                   
1      0      1                                    0   
              2                                    0   
              3                                    0   
              4                                    0   
              5                                    0   

                      ventas_totales_3_meses_pasados  \
pdv_id mes_id sku_id                                   
1      0      1                                    0   
              2                                    0   
              3                                    0   
              4                                    0   
              5                                    0   

                      ventas_totales_tienda_y_mes_del_mes_pasado  ...  \
pdv_id mes_id sku_id                                              ...   
1      0      1                                                0  ...   
              2                                                0  ...   
              3                                                0  ...   
              4                                                0  ...   
              5                                                0  ...   

                      ventas_promedio_tienda_y_mes_del_mes_pasado  \
pdv_id mes_id sku_id                                                
1      0   

In [45]:
# 3.4 CALCULAR ERRORES CON FUNCIONES DE PAQUETERÍA 

# Mean absolute error (MAE)
ent1_mae = mean_absolute_error(ent_1.y_ventas_siguiente_mes, ent_1.ventas_por_mes_pred)

# Mean squared error (MSE)
ent1_mse = mean_squared_error(ent_1.y_ventas_siguiente_mes, ent_1.ventas_por_mes_pred)

# R-squared scores
ent1_r2 = r2_score(ent_1.y_ventas_siguiente_mes, ent_1.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(ent1_mae, 6))
print('Mean Squared Error:', round(ent1_mse, 6))
print('R-squared scores:', round(ent1_r2, 6))

Mean Absolute Error: 0.229267
Mean Squared Error: 0.738406
R-squared scores: 0.276197


----------------------Segunda Partición-------------------------

In [46]:
modelo_2 = tree.DecisionTreeRegressor(max_depth=1)

In [47]:
modelo_2.fit(ent_x2, ent_y2)

DecisionTreeRegressor(max_depth=1)

In [48]:
pred2_ent = modelo_2.predict(ent_x2) 
pred2_ent

array([0.15403151, 0.15403151, 0.15403151, ..., 0.15403151, 0.15403151,
       0.15403151])

In [49]:
pred2_ent = np.clip(pred2_ent,0,20).round() #rango de valores 
pred2_ent

array([0., 0., 0., ..., 0., 0., 0.])

In [50]:
ent_2['ventas_por_mes_pred'] = pred2_ent

In [51]:
ent_2.head(5)

ventas_totales  y_ventas_siguiente_mes  \
pdv_id mes_id sku_id                                           
1      0      1                    1                       1   
       1      1                    1                       0   
       0      2                    0                       2   
       1      2                    2                       1   
       0      3                    0                       1   

                      ventas_totales_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                         
1      0      1                                          1   
       1      1                                          5   
       0      2                                          1   
       1      2                                          5   
       0      3                                          1   

                      ventas_promedio_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                          
1      0      1                                    0.033333   
       1      1                                    0.166667   
       0      2                                    0.033333   
       1      2                                    0.166667   
       0      3                                    0.033333   

                      ventas_totales_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                         
1      0      1                                       2087   
       1      1                                       2106   
       0      2                                        888   
       1      2                                        888   
       0      3                                       1636   

                      ventas_promedio_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                          
1      0      1                                    1.260266   
       1      1                                    1.271739   
       0      2                                    0.536232   
       1      2                                    0.536232   
       0      3                                    0.987923   

                      ventas_totales_1_mes_pasado  \
pdv_id mes_id sku_id                                
1      0      1                                 0   
       1      1                                 1   
       0      2                                 0   
       1      2                                 0   
       0      3                                 0   

                      ventas_totales_2_meses_pasados  \
pdv_id mes_id sku_id                                   
1      0      1                                    0   
       1      1                                    0   
       0      2                                    0   
       1      2                                    0   
       0      3                                    0   

                      ventas_totales_3_meses_pasados  \
pdv_id mes_id sku_id                                   
1      0      1                                    0   
       1      1                                    0   
       0      2                                    0   
       1      2                                    0   
       0      3                                    0   

                      ventas_totales_tienda_y_mes_del_mes_pasado  ...  \
pdv_id mes_id sku_id                                              ...   
1      0      1                                                0  ...   
       1      1                                                1  ...   
       0      2                                                0  ...   
       1      2                                                1  ...   
       0      3                                                0  ...   

                      ventas_promedio_tienda_y_mes_del_mes_pasado  \
pdv_id mes_id sku_id                                                
1      0   

In [52]:
# Mean absolute error (MAE)
ent2_mae = mean_absolute_error(ent_2.y_ventas_siguiente_mes, ent_2.ventas_por_mes_pred)

# Mean squared error (MSE)
ent2_mse = mean_squared_error(ent_2.y_ventas_siguiente_mes, ent_2.ventas_por_mes_pred)

# R-squared scores
ent2_r2 = r2_score(ent_2.y_ventas_siguiente_mes, ent_2.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(ent2_mae, 6))
print('Mean Squared Error:', round(ent2_mse, 6))
print('R-squared scores:', round(ent2_r2, 6))

Mean Absolute Error: 0.220179
Mean Squared Error: 0.737107
R-squared scores: 0.273425


----------------------Tercera Partición-------------------------

In [53]:
modelo_3 = tree.DecisionTreeRegressor(max_depth=1)

In [54]:
modelo_3.fit(ent_x3, ent_y3)

DecisionTreeRegressor(max_depth=1)

In [55]:
pred3_ent = modelo_3.predict(ent_x3) 
pred3_ent

array([0.14773128, 0.14773128, 0.14773128, ..., 0.14773128, 0.14773128,
       0.14773128])

In [56]:
pred3_ent = np.clip(pred3_ent,0,20).round() #rango de valores 
pred3_ent

array([0., 0., 0., ..., 0., 0., 0.])

In [57]:
ent_3['ventas_por_mes_pred'] = pred3_ent

In [58]:
# Mean absolute error (MAE)
ent3_mae = mean_absolute_error(ent_3.y_ventas_siguiente_mes, ent_3.ventas_por_mes_pred)

# Mean squared error (MSE)
ent3_mse = mean_squared_error(ent_3.y_ventas_siguiente_mes, ent_3.ventas_por_mes_pred)

# R-squared scores
ent3_r2 = r2_score(ent_3.y_ventas_siguiente_mes, ent_3.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(ent3_mae, 6))
print('Mean Squared Error:', round(ent3_mse, 6))
print('R-squared scores:', round(ent3_r2, 6))

Mean Absolute Error: 0.207931
Mean Squared Error: 0.640888
R-squared scores: 0.248864


----------------------Cuarta Partición-------------------------

In [59]:
modelo_4 = tree.DecisionTreeRegressor(max_depth=1)

In [60]:
modelo_4.fit(ent_x4, ent_y4)

DecisionTreeRegressor(max_depth=1)

In [61]:
pred4_ent = modelo_4.predict(ent_x4) 
pred4_ent

array([0.15369646, 0.15369646, 0.15369646, ..., 0.15369646, 0.15369646,
       0.15369646])

In [62]:
pred4_ent = np.clip(pred4_ent,0,20).round() #rango de valores 
pred4_ent

array([0., 0., 0., ..., 0., 0., 0.])

In [63]:
ent_4['ventas_por_mes_pred'] = pred4_ent

In [64]:
# Mean absolute error (MAE)
ent4_mae = mean_absolute_error(ent_4.y_ventas_siguiente_mes, ent_4.ventas_por_mes_pred)

# Mean squared error (MSE)
ent4_mse = mean_squared_error(ent_4.y_ventas_siguiente_mes, ent_4.ventas_por_mes_pred)

# R-squared scores
ent4_r2 = r2_score(ent_4.y_ventas_siguiente_mes, ent_4.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(ent4_mae, 6))
print('Mean Squared Error:', round(ent4_mse, 6))
print('R-squared scores:', round(ent4_r2, 6))

Mean Absolute Error: 0.207614
Mean Squared Error: 0.602058
R-squared scores: 0.216246


----------------------Quinta Partición-------------------------

In [65]:
modelo_5 = tree.DecisionTreeRegressor(max_depth=1)

In [66]:
modelo_5.fit(ent_x5, ent_y5)

DecisionTreeRegressor(max_depth=1)

In [67]:
pred5_ent = modelo_5.predict(ent_x5) 
pred5_ent

array([0.13666269, 0.13666269, 0.13666269, ..., 0.13666269, 0.13666269,
       0.13666269])

In [68]:
pred5_ent = np.clip(pred5_ent,0,20).round() #rango de valores 
pred5_ent

array([0., 0., 0., ..., 0., 0., 0.])

In [69]:
ent_5['ventas_por_mes_pred'] = pred5_ent

In [70]:
# Mean absolute error (MAE)
ent5_mae = mean_absolute_error(ent_5.y_ventas_siguiente_mes, ent_5.ventas_por_mes_pred)

# Mean squared error (MSE)
ent5_mse = mean_squared_error(ent_5.y_ventas_siguiente_mes, ent_5.ventas_por_mes_pred)

# R-squared scores
ent5_r2 = r2_score(ent_5.y_ventas_siguiente_mes, ent_5.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(ent5_mae, 6))
print('Mean Squared Error:', round(ent5_mse, 6))
print('R-squared scores:', round(ent5_r2, 6))

Mean Absolute Error: 0.214251
Mean Squared Error: 0.584122
R-squared scores: 0.200806


----------------------Sexta Partición-------------------------

In [71]:
modelo_6 = tree.DecisionTreeRegressor(max_depth=1)

In [72]:
modelo_6.fit(ent_x6, ent_y6)

DecisionTreeRegressor(max_depth=1)

In [73]:
pred6_ent = modelo_6.predict(ent_x6) 
pred6_ent

array([0.14527089, 0.14527089, 0.14527089, ..., 0.14527089, 0.14527089,
       0.14527089])

In [74]:
pred6_ent = np.clip(pred6_ent,0,20).round() #rango de valores 
pred6_ent

array([0., 0., 0., ..., 0., 0., 0.])

In [75]:
ent_6['ventas_por_mes_pred'] = pred6_ent

In [76]:
# Mean absolute error (MAE)
ent6_mae = mean_absolute_error(ent_6.y_ventas_siguiente_mes, ent_6.ventas_por_mes_pred)

# Mean squared error (MSE)
ent6_mse = mean_squared_error(ent_6.y_ventas_siguiente_mes, ent_6.ventas_por_mes_pred)

# R-squared scores
ent6_r2 = r2_score(ent_6.y_ventas_siguiente_mes, ent_6.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(ent6_mae, 6))
print('Mean Squared Error:', round(ent6_mse, 6))
print('R-squared scores:', round(ent6_r2, 6))

Mean Absolute Error: 0.221045
Mean Squared Error: 0.575788
R-squared scores: 0.190119


----------------------Séptima Partición-------------------------

In [77]:
modelo_7 = tree.DecisionTreeRegressor(max_depth=1)

In [78]:
modelo_7.fit(ent_x7, ent_y7)

DecisionTreeRegressor(max_depth=1)

In [79]:
pred7_ent = modelo_7.predict(ent_x7) 
pred7_ent

array([0.14314575, 0.14314575, 0.14314575, ..., 0.14314575, 0.14314575,
       0.14314575])

In [80]:
pred7_ent = np.clip(pred7_ent,0,20).round() #rango de valores 
pred7_ent

array([0., 0., 0., ..., 0., 0., 0.])

In [81]:
ent_7['ventas_por_mes_pred'] = pred7_ent

In [82]:
# Mean absolute error (MAE)
ent7_mae = mean_absolute_error(ent_7.y_ventas_siguiente_mes, ent_7.ventas_por_mes_pred)

# Mean squared error (MSE)
ent7_mse = mean_squared_error(ent_7.y_ventas_siguiente_mes, ent_7.ventas_por_mes_pred)

# R-squared scores
ent7_r2 = r2_score(ent_7.y_ventas_siguiente_mes, ent_7.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(ent7_mae, 6))
print('Mean Squared Error:', round(ent7_mse, 6))
print('R-squared scores:', round(ent7_r2, 6))

Mean Absolute Error: 0.218933
Mean Squared Error: 0.548108
R-squared scores: 0.177641


----------------------Octava Partición-------------------------

In [83]:
modelo_8 = tree.DecisionTreeRegressor(max_depth=1)

In [84]:
modelo_8.fit(ent_x8, ent_y8)

DecisionTreeRegressor(max_depth=1)

In [85]:
pred8_ent = modelo_8.predict(ent_x8) 
pred8_ent

array([0.13826532, 0.13826532, 0.13826532, ..., 0.13826532, 0.13826532,
       0.13826532])

In [86]:
pred8_ent = np.clip(pred8_ent,0,20).round() #rango de valores 
pred8_ent

array([0., 0., 0., ..., 0., 0., 0.])

In [87]:
ent_8['ventas_por_mes_pred'] = pred8_ent

In [88]:
# Mean absolute error (MAE)
ent8_mae = mean_absolute_error(ent_8.y_ventas_siguiente_mes, ent_8.ventas_por_mes_pred)

# Mean squared error (MSE)
ent8_mse = mean_squared_error(ent_8.y_ventas_siguiente_mes, ent_8.ventas_por_mes_pred)

# R-squared scores
ent8_r2 = r2_score(ent_8.y_ventas_siguiente_mes, ent_8.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(ent8_mae, 6))
print('Mean Squared Error:', round(ent8_mse, 6))
print('R-squared scores:', round(ent8_r2, 6))

Mean Absolute Error: 0.211171
Mean Squared Error: 0.512887
R-squared scores: 0.165375


# Prueba de Modelo

In [89]:
# 1. HACER PREDICCIONES: CALCULAR ERROR DE PRUEBA
pred1_prueba = modelo_1.predict(prueba_x1) 
pred1_prueba

array([0.16563895, 0.16563895, 0.16563895, ..., 0.16563895, 0.16563895,
       0.16563895])

In [90]:
# 2. REDONDEAR Y AJUSTAR VALORES
pred1_prueba = np.clip(pred1_prueba,0,20).round() #rango de valores 
pred1_prueba

array([0., 0., 0., ..., 0., 0., 0.])

In [91]:
# ¿Cuántas unidades se van a vender (prediccoión) en ese mes de prueba (en todos los puntos de venta , considerando todos los productos)?
pred1_prueba.sum()

4698.0

In [92]:
# 3. JUNTAR DATOS PARA PODER CALCULAR ERROR
prueba_1['ventas_por_mes_pred'] = pred1_prueba

In [93]:
prueba_1.head(5)

ventas_totales  y_ventas_siguiente_mes  \
pdv_id mes_id sku_id                                           
1      1      1                    1                       0   
              2                    2                       1   
              3                    1                       0   
              4                    1                       0   
              5                    0                       0   

                      ventas_totales_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                         
1      1      1                                          5   
              2                                          5   
              3                                          5   
              4                                          5   
              5                                          5   

                      ventas_promedio_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                          
1      1      1                                    0.166667   
              2                                    0.166667   
              3                                    0.166667   
              4                                    0.166667   
              5                                    0.166667   

                      ventas_totales_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                         
1      1      1                                       2106   
              2                                        888   
              3                                       1808   
              4                                       1338   
              5                                        689   

                      ventas_promedio_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                          
1      1      1                                    1.271739   
              2                                    0.536232   
              3                                    1.091787   
              4                                    0.807971   
              5                                    0.416063   

                      ventas_totales_1_mes_pasado  \
pdv_id mes_id sku_id                                
1      1      1                                 1   
              2                                 0   
              3                                 0   
              4                                 0   
              5                                 0   

                      ventas_totales_2_meses_pasados  \
pdv_id mes_id sku_id                                   
1      1      1                                    0   
              2                                    0   
              3                                    0   
              4                                    0   
              5                                    0   

                      ventas_totales_3_meses_pasados  \
pdv_id mes_id sku_id                                   
1      1      1                                    0   
              2                                    0   
              3                                    0   
              4                                    0   
              5                                    0   

                      ventas_totales_tienda_y_mes_del_mes_pasado  ...  \
pdv_id mes_id sku_id                                              ...   
1      1      1                                                1  ...   
              2                                                1  ...   
              3                                                1  ...   
              4                                                1  ...   
              5                                                1  ...   

                      ventas_promedio_tienda_y_mes_del_mes_pasado  \
pdv_id mes_id sku_id                                                
1      1   

In [94]:
# 4. CALCULAR ERRORES CON FUNCIONES DE PAQUETERÍA

# Mean absolute error (MAE)
prueba1_mae = mean_absolute_error(prueba_1.y_ventas_siguiente_mes, prueba_1.ventas_por_mes_pred)

# Mean squared error (MSE)
prueba1_mse = mean_squared_error(prueba_1.y_ventas_siguiente_mes, prueba_1.ventas_por_mes_pred)

# R-squared scores
prueba1_r2 = r2_score(prueba_1.y_ventas_siguiente_mes, prueba_1.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(prueba1_mae, 6))
print('Mean Squared Error:', round(prueba1_mse, 6))
print('R-squared scores:', round(prueba1_r2, 6))

Mean Absolute Error: 0.211091
Mean Squared Error: 0.735809
R-squared scores: 0.2704


----------------------Segunda Partición-------------------------

In [95]:
pred2_prueba = modelo_2.predict(prueba_x2) 
pred2_prueba

array([0.15403151, 0.15403151, 0.15403151, ..., 0.15403151, 0.15403151,
       0.15403151])

In [96]:
pred2_prueba = np.clip(pred2_prueba,0,20).round() #rango de valores 
pred2_prueba

array([0., 0., 0., ..., 0., 0., 0.])

In [97]:
pred2_prueba.sum()

4218.0

In [98]:
prueba_2['ventas_por_mes_pred'] = pred2_prueba

In [99]:
# Mean absolute error (MAE)
prueba2_mae = mean_absolute_error(prueba_2.y_ventas_siguiente_mes, prueba_2.ventas_por_mes_pred)

# Mean squared error (MSE)
prueba2_mse = mean_squared_error(prueba_2.y_ventas_siguiente_mes, prueba_2.ventas_por_mes_pred)

# R-squared scores
prueba2_r2 = r2_score(prueba_2.y_ventas_siguiente_mes, prueba_2.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(prueba2_mae, 6))
print('Mean Squared Error:', round(prueba2_mse, 6))
print('R-squared scores:', round(prueba2_r2, 6))

Mean Absolute Error: 0.183434
Mean Squared Error: 0.44845
R-squared scores: 0.151211


----------------------Tercera Partición-------------------------

In [100]:
pred3_prueba = modelo_3.predict(prueba_x3) 
pred3_prueba

array([0.14773128, 0.14773128, 0.14773128, ..., 0.14773128, 0.14773128,
       0.14773128])

In [101]:
pred3_prueba = np.clip(pred3_prueba,0,20).round() #rango de valores 
pred3_prueba

array([0., 0., 0., ..., 0., 0., 0.])

In [102]:
pred3_prueba.sum()

3063.0

In [103]:
prueba_3['ventas_por_mes_pred'] = pred3_prueba

In [104]:
# Mean absolute error (MAE)
prueba3_mae = mean_absolute_error(prueba_3.y_ventas_siguiente_mes, prueba_3.ventas_por_mes_pred)

# Mean squared error (MSE)
prueba3_mse = mean_squared_error(prueba_3.y_ventas_siguiente_mes, prueba_3.ventas_por_mes_pred)

# R-squared scores
prueba3_r2 = r2_score(prueba_3.y_ventas_siguiente_mes, prueba_3.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(prueba3_mae, 6))
print('Mean Squared Error:', round(prueba3_mse, 6))
print('R-squared scores:', round(prueba3_r2, 6))

Mean Absolute Error: 0.206663
Mean Squared Error: 0.485568
R-squared scores: 0.052811


----------------------Cuarta Partición-------------------------

In [105]:
pred4_prueba = modelo_4.predict(prueba_x4) 
pred4_prueba

array([0.15369646, 0.15369646, 0.15369646, ..., 0.15369646, 0.15369646,
       0.15369646])

In [106]:
pred4_prueba = np.clip(pred4_prueba,0,20).round() #rango de valores 
pred4_prueba

array([0., 0., 0., ..., 0., 0., 0.])

In [107]:
pred4_prueba.sum()

2955.0

In [108]:
prueba_4['ventas_por_mes_pred'] = pred4_prueba

In [109]:
# Mean absolute error (MAE)
prueba4_mae = mean_absolute_error(prueba_4.y_ventas_siguiente_mes, prueba_4.ventas_por_mes_pred)

# Mean squared error (MSE)
prueba4_mse = mean_squared_error(prueba_4.y_ventas_siguiente_mes, prueba_4.ventas_por_mes_pred)

# R-squared scores
prueba4_r2 = r2_score(prueba_4.y_ventas_siguiente_mes, prueba_4.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(prueba4_mae, 6))
print('Mean Squared Error:', round(prueba4_mse, 6))
print('R-squared scores:', round(prueba4_r2, 6))

Mean Absolute Error: 0.244887
Mean Squared Error: 0.581602
R-squared scores: -0.000113


----------------------Quinta Partición-------------------------

In [110]:
pred5_prueba = modelo_5.predict(prueba_x5) 
pred5_prueba

array([0.13666269, 0.13666269, 0.13666269, ..., 0.13666269, 0.13666269,
       0.13666269])

In [111]:
pred5_prueba = np.clip(pred5_prueba,0,20).round() #rango de valores 
pred5_prueba

array([0., 0., 0., ..., 0., 0., 0.])

In [112]:
pred5_prueba.sum()

5154.0

In [113]:
prueba_5['ventas_por_mes_pred'] = pred5_prueba

In [114]:
# Mean absolute error (MAE)
prueba5_mae = mean_absolute_error(prueba_5.y_ventas_siguiente_mes, prueba_5.ventas_por_mes_pred)

# Mean squared error (MSE)
prueba5_mse = mean_squared_error(prueba_5.y_ventas_siguiente_mes, prueba_5.ventas_por_mes_pred)

# R-squared scores
prueba5_r2 = r2_score(prueba_5.y_ventas_siguiente_mes, prueba_5.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(prueba5_mae, 6))
print('Mean Squared Error:', round(prueba5_mse, 6))
print('R-squared scores:', round(prueba5_r2, 6))

Mean Absolute Error: 0.255012
Mean Squared Error: 0.534118
R-squared scores: 0.124621


----------------------Sexta Partición-------------------------

In [115]:
pred6_prueba = modelo_6.predict(prueba_x6) 
pred6_prueba

array([0.14527089, 0.14527089, 0.14527089, ..., 0.14527089, 0.14527089,
       0.14527089])

In [116]:
pred6_prueba = np.clip(pred6_prueba,0,20).round() #rango de valores 
pred6_prueba

array([0., 0., 0., ..., 0., 0., 0.])

In [117]:
pred6_prueba.sum()

5720.0

In [118]:
prueba_6['ventas_por_mes_pred'] = pred6_prueba

In [119]:
# Mean absolute error (MAE)
prueba6_mae = mean_absolute_error(prueba_6.y_ventas_siguiente_mes, prueba_6.ventas_por_mes_pred)

# Mean squared error (MSE)
prueba6_mse = mean_squared_error(prueba_6.y_ventas_siguiente_mes, prueba_6.ventas_por_mes_pred)

# R-squared scores
prueba6_r2 = r2_score(prueba_6.y_ventas_siguiente_mes, prueba_6.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(prueba6_mae, 6))
print('Mean Squared Error:', round(prueba6_mse, 6))
print('R-squared scores:', round(prueba6_r2, 6))

Mean Absolute Error: 0.20626
Mean Squared Error: 0.382025
R-squared scores: 0.040724


----------------------Séptima Partición-------------------------

In [120]:
pred7_prueba = modelo_7.predict(prueba_x7) 
pred7_prueba

array([0.14314575, 0.14314575, 0.14314575, ..., 0.14314575, 0.14314575,
       0.14314575])

In [121]:
pred7_prueba = np.clip(pred7_prueba,0,20).round() #rango de valores 
pred7_prueba

array([0., 0., 0., ..., 0., 0., 0.])

In [122]:
pred7_prueba.sum()

3806.0

In [123]:
prueba_7['ventas_por_mes_pred'] = pred7_prueba

In [124]:
# Mean absolute error (MAE)
prueba7_mae = mean_absolute_error(prueba_7.y_ventas_siguiente_mes, prueba_7.ventas_por_mes_pred)

# Mean squared error (MSE)
prueba7_mse = mean_squared_error(prueba_7.y_ventas_siguiente_mes, prueba_7.ventas_por_mes_pred)

# R-squared scores
prueba7_r2 = r2_score(prueba_7.y_ventas_siguiente_mes, prueba_7.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(prueba7_mae, 6))
print('Mean Squared Error:', round(prueba7_mse, 6))
print('R-squared scores:', round(prueba7_r2, 6))

Mean Absolute Error: 0.156844
Mean Squared Error: 0.266345
R-squared scores: -0.096035


----------------------Octava Partición-------------------------

In [125]:
pred8_prueba = modelo_8.predict(prueba_x8) 
pred8_prueba

array([0.13826532, 0.13826532, 0.13826532, ..., 0.13826532, 0.13826532,
       0.13826532])

In [126]:
pred8_prueba = np.clip(pred8_prueba,0,20).round() #rango de valores 
pred8_prueba

array([0., 0., 0., ..., 0., 0., 0.])

In [127]:
pred8_prueba.sum()

2462.0

In [128]:
prueba_8['ventas_por_mes_pred'] = pred8_prueba

In [129]:
# Mean absolute error (MAE)
prueba8_mae = mean_absolute_error(prueba_8.y_ventas_siguiente_mes, prueba_8.ventas_por_mes_pred)

# Mean squared error (MSE)
prueba8_mse = mean_squared_error(prueba_8.y_ventas_siguiente_mes, prueba_8.ventas_por_mes_pred)

# R-squared scores
prueba8_r2 = r2_score(prueba_8.y_ventas_siguiente_mes, prueba_8.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(prueba8_mae, 6))
print('Mean Squared Error:', round(prueba8_mse, 6))
print('R-squared scores:', round(prueba8_r2, 6))

Mean Absolute Error: 0.094082
Mean Squared Error: 0.15467
R-squared scores: -0.594269


# Fin Parte 1